version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
        MYSQL_DATABASE: desafio
        MYSQL_USER: desafio
        MYSQL_PASSWORD: desafio
        MYSQL_ROOT_PASSWORD: root
